import ToDoList from '../components/ToDoList'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useAuth } from '@clerk/nextjs'
import NavBar from '../components/NavBar'
import { useEffect } from "react"

export default function Done() {
  const { isLoaded, userId, sessionId, getToken } = useAuth();
  const router = useRouter()

  useEffect(() => {
    if(!userId){
      router.push('/')
    }
  });

    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
          <link rel="manifest" href="/site.webmanifest"></link>
        </Head>
        <NavBar/>
        <ToDoList done={true}/>
      </>
    ) 
  }