import { Inter } from 'next/font/google'
import { useAuth, SignIn } from '@clerk/nextjs'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import purpleBlob from '../../public/purpleblob.svg'
import orangeBlob from '../../public/orangeBlob2.svg'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { isLoaded, userId, sessionId, getToken } = useAuth();
  const router = useRouter()

  // user is logged in, automatically redirect to /todos
  if(userId){
    router.push('/todos')
  } 
  // user is not logged in, render root page with title and clerk signIn
  else {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
          <link rel="manifest" href="/site.webmanifest"></link>
          {/* <link rel='stylesheet' href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"></link> */}
        </Head>

        <div className="splash-container">
          <div className="splash-header-container">
            <div className="splash-orange-blob-container">
              <Image className="splash-orange-blob" fill src={orangeBlob}/>
            </div>

            <div className="splash-purple-blob-container">
              <Image className="splash-purple-blob" fill src={purpleBlob}/>
            </div>
            
            <span className="splash-title1">Isabel's</span>
            <span className="splash-title2">Task List!</span>

          </div>
                    
          <SignIn className="splash-signIn"/>
        </div>
      </>
    )
  }
  
}
